name: Node - SSH deploy

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    SFTP-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest

        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: Use Node.js 16
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '16'

            - name: 🔨 Build Project
              run: |
                  yarn
                  yarn build

            # - name: 📂 Deploy to Server
              # uses: 
              # env:
              #     SSH_PRIVATE_KEY: 
              #     SOURCE: 'build/'
              #     REMOTE_HOST: 
              #     REMOTE_USER: 
              #     TARGET: 
              #     EXCLUDE: '/dist/, /node_modules/'
